export const ENDPOINTS = {
  departments: '/api/departments',
  department: (id) => `/api/departments/${id}`,
  categories: (type) => `/api/categories?type=${type}`,
  emissionFactors: '/api/emission-factors',
  goals: (departmentId) => `/api/goals?department_id=${departmentId}`,
  policies: '/api/policies',
  badges: '/api/badges',
  rewards: '/api/rewards',
  carbonTransactions: (params = '') => `/api/carbon-transactions${params}`,
  csrActivities: '/api/csr-activities',
  joinCsrActivity: (id) => `/api/csr-activities/${id}/join`,
  approveParticipation: (id) => `/api/participations/${id}/approve`,
  rejectParticipation: (id) => `/api/participations/${id}/reject`,
  challenges: (status) => `/api/challenges${status ? `?status=${status}` : ''}`,
  joinChallenge: (id) => `/api/challenges/${id}/join`,
  challengeProgress: (id) => `/api/challenge-participations/${id}/progress`,
  approveChallengeParticipation: (id) => `/api/challenge-participations/${id}/approve`,
  employeeXp: (employeeId) => `/api/employees/${employeeId}/xp`,
  employeeBadges: (employeeId) => `/api/employees/${employeeId}/badges`,
  leaderboard: (deptId = '', period = '') => `/api/leaderboard?department_id=${deptId}&period=${period}`,
  redeemReward: (id) => `/api/rewards/${id}/redeem`,
  acknowledgePolicy: (id) => `/api/policies/${id}/acknowledge`,
  audits: '/api/audits',
  complianceIssues: (status) => `/api/compliance-issues${status ? `?status=${status}` : ''}`,
  complianceIssue: (id) => `/api/compliance-issues/${id}`,
  departmentScore: (id) => `/api/departments/${id}/score`,
  organizationScore: '/api/organization/score',
  dashboardSummary: '/api/dashboard/summary',
  report: (type, params = '') => `/api/reports/${type}${params}`,
  customReport: '/api/reports/custom',
  exportReport: (id, format) => `/api/reports/${id}/export?format=${format}`,
  esgSettings: '/api/settings/esg',
  notificationSettings: '/api/settings/notifications',
  quizzes: '/api/quizzes',
  quiz: (id) => `/api/quizzes/${id}`,
  quizQuestions: (quizId) => `/api/quizzes/${quizId}/questions`,
  startQuiz: (quizId) => `/api/quizzes/${quizId}/start`,
  submitQuiz: (participationId) => `/api/quizzes/participations/${participationId}/submit`,
};